"use client";

import { DataPage, StatusBadge } from "@/components/data-page";

export default function NotificationsPage() {
  return (
    <DataPage
      title="Notifications"
      description="In-app notifications generated by reminders and platform events."
      endpoint="/api/notifications?includeRead=true"
      columns={[
        { key: "title", label: "Notification" },
        { key: "type", label: "Type" },
        { key: "severity", label: "Severity", render: (item) => <StatusBadge value={item.severity} /> },
        { key: "status", label: "Status", render: (item) => <StatusBadge value={item.status} /> },
        { key: "createdUtc", label: "Created" }
      ]}
    />
  );
}
