// <auto-generated />
using System;
using Companion.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Companion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CompanionDbContext))]
    [Migration("20260619141733_CompanionBrainSpine")]
    partial class CompanionBrainSpine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Companion.Core.Entities.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("Status", "CreatedUtc");

                    b.ToTable("AgentRuns");
                });

            modelBuilder.Entity("Companion.Core.Entities.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ReviewedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("SourceMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SourceMessageId");

                    b.HasIndex("UserProfileId", "Status", "CreatedUtc");

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("Companion.Core.Entities.ConnectorAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "Status");

                    b.ToTable("ConnectorAccounts");
                });

            modelBuilder.Entity("Companion.Core.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveTopic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastMessageUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "LastMessageUtc");

                    b.ToTable("Conversations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d5359f4-09b2-4351-9c8d-c4c34b19d74f"),
                            ActiveTopic = "Companion Core Onboarding",
                            CreatedUtc = new DateTime(2026, 6, 19, 12, 5, 0, 0, DateTimeKind.Utc),
                            LastMessageUtc = new DateTime(2026, 6, 19, 12, 5, 0, 0, DateTimeKind.Utc),
                            Title = "Companion Core Onboarding",
                            UpdatedUtc = new DateTime(2026, 6, 19, 12, 5, 0, 0, DateTimeKind.Utc),
                            UserProfileId = new Guid("2d76812e-4f4f-4313-a368-5dcb29b4bf3f")
                        });
                });

            modelBuilder.Entity("Companion.Core.Entities.MemoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Importance")
                        .HasColumnType("integer");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastReferencedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sensitivity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "IsArchived", "Type");

                    b.ToTable("MemoryEntries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f761be7-f7c7-4bd3-bff5-6f3aa08e09aa"),
                            Confidence = 0.93m,
                            Content = "The local user prefers direct, high-signal summaries during development work.",
                            CreatedUtc = new DateTime(2026, 6, 19, 12, 10, 0, 0, DateTimeKind.Utc),
                            Importance = 4,
                            IsArchived = false,
                            LastReferencedUtc = new DateTime(2026, 6, 19, 12, 10, 0, 0, DateTimeKind.Utc),
                            Sensitivity = "Normal",
                            Source = "Seed",
                            Summary = "Prefers concise status updates",
                            Type = "Preference",
                            UserProfileId = new Guid("2d76812e-4f4f-4313-a368-5dcb29b4bf3f")
                        },
                        new
                        {
                            Id = new Guid("e550806f-384c-4104-84c9-f5cff8297900"),
                            Confidence = 0.98m,
                            Content = "Companion Core is the backend foundation for a private AI companion platform.",
                            CreatedUtc = new DateTime(2026, 6, 19, 12, 11, 0, 0, DateTimeKind.Utc),
                            Importance = 5,
                            IsArchived = false,
                            LastReferencedUtc = new DateTime(2026, 6, 19, 12, 11, 0, 0, DateTimeKind.Utc),
                            Sensitivity = "Normal",
                            Source = "Seed",
                            Summary = "Building Companion Core",
                            Type = "Project",
                            UserProfileId = new Guid("2d76812e-4f4f-4313-a368-5dcb29b4bf3f")
                        },
                        new
                        {
                            Id = new Guid("de687616-b0c7-4715-9a31-c1e1fc792532"),
                            Confidence = 0.88m,
                            Content = "The local user responds well to supportive, practical progress updates while building software.",
                            CreatedUtc = new DateTime(2026, 6, 19, 12, 12, 0, 0, DateTimeKind.Utc),
                            Importance = 3,
                            IsArchived = false,
                            Sensitivity = "Normal",
                            Source = "Seed",
                            Summary = "Likes collaborative momentum",
                            Type = "Style",
                            UserProfileId = new Guid("2d76812e-4f4f-4313-a368-5dcb29b4bf3f")
                        });
                });

            modelBuilder.Entity("Companion.Core.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("TokensEstimate")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedUtc");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Companion.Core.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("DueDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("SourceMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceMessageId");

                    b.HasIndex("UserProfileId", "Status", "DueDateUtc");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7fd0e94-87ba-42ed-a0f7-f8ce8b2d4cc4"),
                            CreatedUtc = new DateTime(2026, 6, 19, 12, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Confirm the core endpoints match the first Companion Core backend milestone.",
                            DueDateUtc = new DateTime(2026, 6, 20, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            Status = "Todo",
                            Title = "Review the initial API surface",
                            UserProfileId = new Guid("2d76812e-4f4f-4313-a368-5dcb29b4bf3f")
                        },
                        new
                        {
                            Id = new Guid("9995cd58-1841-4732-8c87-34a6334f6652"),
                            CreatedUtc = new DateTime(2026, 6, 19, 12, 16, 0, 0, DateTimeKind.Utc),
                            Description = "Create a sample approval request and verify it can be approved or rejected.",
                            DueDateUtc = new DateTime(2026, 6, 21, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "Normal",
                            Status = "InProgress",
                            Title = "Exercise the approval workflow",
                            UserProfileId = new Guid("2d76812e-4f4f-4313-a368-5dcb29b4bf3f")
                        },
                        new
                        {
                            Id = new Guid("0ec7d330-08fb-44fe-9b34-e0075ef75f8a"),
                            CreatedUtc = new DateTime(2026, 6, 19, 12, 17, 0, 0, DateTimeKind.Utc),
                            Description = "Queue a pending agent run and confirm the worker moves it to completed.",
                            DueDateUtc = new DateTime(2026, 6, 22, 17, 0, 0, 0, DateTimeKind.Utc),
                            Priority = "High",
                            Status = "Todo",
                            Title = "Observe worker-driven agent runs",
                            UserProfileId = new Guid("2d76812e-4f4f-4313-a368-5dcb29b4bf3f")
                        });
                });

            modelBuilder.Entity("Companion.Core.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d76812e-4f4f-4313-a368-5dcb29b4bf3f"),
                            CreatedUtc = new DateTime(2026, 6, 19, 12, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Local User",
                            Email = "local.user@companion-core.local",
                            UpdatedUtc = new DateTime(2026, 6, 19, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Companion.Core.Entities.AgentRun", b =>
                {
                    b.HasOne("Companion.Core.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Companion.Core.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Companion.Core.Entities.ApprovalRequest", b =>
                {
                    b.HasOne("Companion.Core.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Companion.Core.Entities.Message", null)
                        .WithMany()
                        .HasForeignKey("SourceMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Companion.Core.Entities.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Companion.Core.Entities.Conversation", b =>
                {
                    b.HasOne("Companion.Core.Entities.UserProfile", "UserProfile")
                        .WithMany("Conversations")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Companion.Core.Entities.MemoryEntry", b =>
                {
                    b.HasOne("Companion.Core.Entities.UserProfile", "UserProfile")
                        .WithMany("MemoryEntries")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Companion.Core.Entities.Message", b =>
                {
                    b.HasOne("Companion.Core.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Companion.Core.Entities.TaskItem", b =>
                {
                    b.HasOne("Companion.Core.Entities.Message", null)
                        .WithMany()
                        .HasForeignKey("SourceMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Companion.Core.Entities.UserProfile", "UserProfile")
                        .WithMany("Tasks")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Companion.Core.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Companion.Core.Entities.UserProfile", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("MemoryEntries");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
